image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG_APP: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  IMAGE_TAG_FRONT: $CI_REGISTRY_IMAGE:front-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker images

stages:
  - build
  - publish
  - deploy
  - clean

build:
  stage: build
  script:
    - cd webapp
    - docker build -t $IMAGE_TAG_APP .
    - echo "Bingo !"
  only:
    - develop
    - master   
    
publish:
  stage: publish
  script:
    - echo "publishing"
    - docker push $IMAGE_TAG_APP
  only:
    - develop
    - master
deploy:
  stage: deploy
  script:
    - echo "No Deployment configured yet"
  only:
    - develop
    - master

clean:
  stage: clean
  script:
    - pwd
    - rm -fr *