image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG_APP: $CI_REGISTRY_IMAGE:app-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker images

stages:
  - build
  - publish
  - deploy
  - clean

build:
  stage: build
  script:
    - cd webapp
    - docker build -t $IMAGE_TAG_APP .
    - echo "Bingo !"
  only:
    - develop
    - master   
    
publish:
  stage: publish
  script:
    - echo "publishing"
    - docker push $IMAGE_TAG_APP
  only:
    - develop
    - master
deploy:
  stage: deploy
  script:
    - kubectl config set-cluster insiderlabs-app-dev --server="$KUBE_URL_DEV" --insecure-skip-tls-verify=true
    - kubectl config set-credentials $KUBE_API_USER_DEV --token=$KUBE_API_TOKEN_DEV
    - kubectl config set-context insiderlabs-app-dev --cluster insiderlabs-app-dev --namespace=insider-labs --user $KUBE_API_USER_DEV
    - kubectl config use-context insiderlabs-app-dev
    - kubectl config current-context
    - kubectl config view
    - kubectl set image deployment/insiderlabs-app insiderlabs-app=$IMAGE_TAG_APP
    - kubectl rollout status deployment.v1.apps/insiderlabs-app
  only:
    - develop
    - master


clean:
  stage: clean
  script:
    - pwd
    - rm -fr *