apiVersion: apps/v1
kind: Deployment
metadata:
  name: insiderlabs-app
  namespace: insider-labs
  labels:
    app: insiderlabs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insiderlabs-app
  template:
    metadata:
      labels:
        app: insiderlabs-app
    spec:
      containers:
      - name: insiderlabs-app
        image: registry.gitlab.com/insider-labs/insiderlabs-app:app-develop-9f6c52a6
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-insider-labs
