apiVersion: apps/v1
kind: Deployment
metadata:
  name: insiderlabs-app
  namespace: insider-labs
  labels:
    app: insiderlabs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insiderlabs-app
  template:
    metadata:
      labels:
        app: insiderlabs-app
    spec:
      containers:
      - name: insiderlabs-app
        image: registry.gitlab.com/insider-labs/insiderlabs-app:app-develop-9f6c52a6
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: gitlab-insiderlabs-app
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: insiderlabs-app
  namespace: insider-labs
  resourceVersion: "751199"
  uid: 376d489d-e11e-4351-9efa-8bf347ae4d8c
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`insiderlabs-app.alpha.n-marketing.io`)
    passHostHeader: false
    services:
    - name: insiderlabs-app
      port: 3000
  tls:
    certResolver: default
