
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: insiderlabs-app
  name: insiderlabs-app
  namespace: insider-labs
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: insiderlabs-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: insiderlabs-app
    spec:
      containers:
        image: registry.gitlab.com/insider-labs/
        imagePullPolicy: IfNotPresent
        name: insiderlabs-app
        ports:
        - containerPort: 3000
          protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-insider-labs
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30